name: Build and Push Images to GHCR

on:
  push:
    branches:
      - *
#      - main
#  pull_request:
#    branches:
#      - main

env:
  buildx_version: v0.30.1 # github-releases:docker/buildx
  kubectl_version: v1.34.2 # github-releases:kubernetes/kubernetes
  helm_version: v3.19.2 # github-releases:helm/helm
  ct_version: v3.14.0 # github-releases:helm/chart-testing
  kind_version: v0.30.0 # github-releases:kubernetes-sigs/kind
  kustomize_version: v5.6.0 # github-releases:kubernetes-sigs/kustomize:kustomize/(?<version>.*)
  kubeseal_version: v0.33.1 # github-releases:bitnami-labs/sealed-secrets
  argocd_version: v3.2.0 # github-releases:argoproj/argo-cd
  ansible_version: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platforms: ["linux/amd64,linux/arm64"]
        image: ["dind-buildx", "dind-buildx-helm", "dind-buildx-helm-kind", "dind-helm", "dind-helm-kind"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./images/${{ matrix.image }}/Dockerfile
          push: true
          tags: ghcr.io/sickhub/${{ matrix.image }}:${{ matrix.version }}
          platforms: ${{ matrix.platforms }}
          build-args: |
            "BUILDX_VERSION=${{ env.buildx_version }}"
            "KUBECTL_VERSION=${{ env.kubectl_version }}"
            "HELM_VERSION=${{ env.helm_version }}"
            "CT_VERSION=${{ env.ct_version }}"
            "KIND_VERSION=${{ env.kind_version }}"
            "KUSTOMIZE_VERSION=${{ env.kustomize_version }}"
            "KUBESEAL_VERSION=${{ env.kubeseal_version }}"
